@host = http://localhost:2012
//@host = https://api.launch-control.eventivize.co
@token = 8d0a2f8305a8ce41947b166b1ab46c77c4945e5269dc393301e94f1cf0595b7b
@eventID = co3-91851c78f1f03d2943a0

### general routes
GET {{host}}/

### api status
GET {{host}}/api/status

### Create an event
POST {{host}}/api/v1/events
Content-Type: application/json
X-Lctrld-Token: {{token}}

{
    "token_symbol": "CO3",
    "genesis_accounts": [
        {
            "name": "Martha Pistacho",
            "genesis_balance": "20"
        },
        {
            "name": "Johny Pistacho"
        }
    ]
}

### List events
GET {{host}}/api/v1/events
X-Lctrld-Token: {{token}}

### Get single event
GET {{host}}/api/v1/events/{{eventID}}
X-Lctrld-Token: {{token}}

### Delete an Event
DELETE {{host}}/api/v1/events/{{eventID}}
X-Lctrld-Token: {{token}}

### USER MANAGEMENT
@email = no.andrea@gmail.com
@pass = whatever

### Register a user 
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "{{email}}",
    "pass" : "{{pass}}"
}

### Login 
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "pass" : "{{pass}}"
}

### Logout 
POST {{host}}/api/v1/auth/logout
Content-Type: application/json
