//@host = http://localhost:2012
@host = https://api.launch-control.eventivize.co
@token = 830a3553a5570debd59e5224ff84df03454621a6218c237a3b852debaa3cbf0b

### Create an event
@eventID = x
POST {{host}}/api/v1/events
Content-Type: application/json
X-Lctrld-Token: {{token}}

{
    "owner": "andrea@apeunit.com",
    "token": "CO3",
    "accounts": [
        {
            "name": "Martha Pistacho",
        },
        {
            "name": "Johny Pistacho",
        }
    ]
}

### List events
GET {{host}}/api/v1/events
X-Lctrld-Token: {{token}}

### Get single event
@eventID = x
GET {{host}}/api/v1/events/{{eventID}}
X-Lctrld-Token: {{token}}

### Delete an Event
DELETE {{host}}/api/v1/events/{{eventID}}
X-Lctrld-Token: {{token}}


### USER MANAGEMENT
@email = no.andreo@gmail.com
@pass = whatever

### Register a user 
POST {{host}}/api/v1/auth/register
Content-Type: application/json

{
    "email": "{{email}}",
    "pass" : "{{pass}}"
}

### Login 
POST {{host}}/api/v1/auth/login
Content-Type: application/json

{
    "email": "{{email}}",
    "pass" : "{{pass}}"
}

### Logout 
POST {{host}}/api/v1/auth/logout
Content-Type: application/json
